name: Codecov

on:
  workflow_dispatch:
  push:
    branches: 
      - 'main'

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      # Set up
      - uses: actions/checkout@v2
      # Tasks
      - name: Upload them to Codecov
        run: bash <(curl -s https://codecov.io/bash) -t ${{ secrets.CODECOV_TOKEN }}

