name: Codecov

on:
  workflow_dispatch:
  push:
    branches: 
      - 'main'

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      # Set up
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v1
      - uses: actions/cache@v1
        with:
          path: opt/hostedtoolcache/flutter
          key: ${{ runner.os }}-flutter
      # Tasks
      - name: Build Runner
        run: flutter pub run build_runner build --delete-conflicting-outputs
      - name: Tests
        run: flutter test --coverage
      # Tasks
      - name: Upload them to Codecov
        run: bash <(curl -s https://codecov.io/bash) -t ${{ secrets.CODECOV_TOKEN }}

