name: Validate PR

on:
  workflow_dispatch:
  pull_request:
    types:
      - opened
      - ready_for_review
    branches: 
      - 'main'

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      # Set up
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v1
      - uses: actions/cache@v1
        with:
          path: opt/hostedtoolcache/flutter
          key: ${{ runner.os }}-flutter
      # Tasks
      - name: Analyze
        run: flutter analyze
      - name: Check format
        run: flutter format lib --set-exit-if-changed
      - name: Build Runner
        run: flutter pub run build_runner build --delete-conflicting-outputs
      - name: Tests
        run: flutter test
